apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: vote
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: hgyang25/vote-app
    newTag: v1.0.0
  - name: hgyang25/result-app
    newTag: v1.0.0
  - name: hgyang25/worker-app
    newTag: v1.0.0
