apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../base

images:
  - name: hgyang25/vote-app
    newTag: dev
  - name: hgyang25/result-app
    newTag: dev
  - name: hgyang25/worker-app
    newTag: dev
