apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../base



images:
- name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/result-app
  newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/result-app
  newTag: bedf59864c57597fbffdc735340f5730bd1654d5
- name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote-app
  newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote-app
  newTag: bedf59864c57597fbffdc735340f5730bd1654d5
- name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/worker-app
  newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/worker-app
  newTag: bedf59864c57597fbffdc735340f5730bd1654d5
