apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../base

images:
  - name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote-app
    newTag: dev

  - name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/result-app
    newTag: dev

  - name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/worker-app
    newTag: dev
